### ISSUE TITLE
Using the advanced filter: how to import the entire article into Logseq?

### ISSUE THREAD

**Issue by djeear-github** [omnivore-app/logseq-omnivore#102]
In addition to highlights and notes, what is the best way to get also the entire article into Logseq?
I only want to import articles with the label: Sent2Logseq. So I must use the advanced filter. Until now the only work around I can find is highlighting the complete article before I sent it to Logseq, but then it is not possible for me to use specific highlights.

**Comment by jacksonh** [comment]
Hi @djeear-github can you try adding `{{{ content }}}` to your template, that should import the content of the article as markdown.

**Comment by djeear-github** [comment]
Hi jacksonh,
I had seen the documentation, but did not understand it. When I add {{{ content }}} to the template it works very good.
