### ISSUE TITLE
Simply does not work.

### ISSUE THREAD

**Issue by iorgaantonio** [omnivore-app/logseq-omnivore#104]
I have installed today the omnivore plugin for the first time. Added the API key and tried to sync my highlights but they don't. Omnivore page is note created, and when I click the plug-in I get the "Omnivore is already syncing" message but it doesn't.

**Comment by iorgaantonio** [comment]
I will add some context to the issue. It's happening on a Macbook with Intel CPU and MacOS 13.2. The Logseq app is version 0.9.6 (0.9.6) and Omnivore plugin v1.12.5. I'v tried reinstalling a couple times but still does not work. If I can provide any more information feel free to ask me.

**Comment by iorgaantonio** [comment]
It just started working without any change.

**Comment by lencioni** [comment]
I had the same experience today, and after quitting logseq and opening it again, the initial sync worked pretty quickly.

I wonder if this indicates a bug of some sort, or if this is not fixable then perhaps it should be added to the installation/usage instructions?
