### ISSUE TITLE
Change the heading of articles `## 🔖 Articles` 

### ISSUE THREAD

**Issue by sywhb** [omnivore-app/logseq-omnivore#106]

**Comment by luismcv** [comment]
It'd be good as well if it could be optionally disabled all together. If you save each article on a separate page you don't need this top block on it.

**Comment by yitsushi** [comment]
When `isSinglePage` is false, it's 100% an unnecessary clutter.

**Comment by yitsushi** [comment]
I'm far from being competent with TS and how Logseq works, so I'll not open a PR about it as I know I'll not be able to address deeper issues about it, but I think that should a good starting point:
```diff
❯ git diff src
diff --git a/src/index.ts b/src/index.ts
index 50c9737..2643725 100644
--- a/src/index.ts
+++ b/src/index.ts
@@ -239,7 +239,8 @@ const fetchOmnivore = async (inBackground = false) => {
           pageName = replaceIllegalChars(
             renderPageName(article, pageNameTemplate, preferredDateFormat)
           )
-          targetBlockId = (await getOmnivoreBlock(pageName, blockTitle)).uuid
+          const page = await getOmnivorePage(pageName)
+          targetBlockId = page.uuid
         }
         const articleBatch = articleBatchMap.get(targetBlockId) || []
         // render article content
@@ -415,7 +416,8 @@ const fetchOmnivore = async (inBackground = false) => {
             pageNameTemplate,
             preferredDateFormat
           )
-          targetBlockId = (await getOmnivoreBlock(pageName, blockTitle)).uuid
+          const page = await getOmnivorePage(pageName)
+          targetBlockId = page.uuid

           // delete page if article is synced to a separate page and page is not a journal
           const existingPage = await logseq.Editor.getPage(pageName)
```
I'm sure I'm missing things that has to be updated to achieve this.

**Comment by sywhb** [comment]
Hey @yitsushi, thanks for inspiration and I have made some changes based on your code.

A new version of the plugin `v1.14.0` is just released and I have added a setting for people to customize the heading.

<img width="676" alt="Screenshot 2023-10-25 at 11 00 47 AM" src="https://github.com/omnivore-app/logseq-omnivore/assets/12963965/a16facdb-2d0f-4fa2-82fc-a80a6582c058">
