### ISSUE TITLE
replace `content` with `highlighted content`

### ISSUE THREAD

**Issue by sywhb** [omnivore-app/logseq-omnivore#107]

**Comment by jacksonh** [comment]
Honestly, not sure if we need to do this one, I had just assumed it was a different name.

**Comment by sywhb** [comment]
lol my bad. @jacksonh I meant use highlightedMarkdown for the `content`

**Comment by jacksonh** [comment]
oh got it! And I just realized which repo this is on.

**Comment by yoghurtdewdew** [comment]
Wow there can be Highlightedmarkdown content? But now I could not get any content, why?

May related #114 https://github.com/omnivore-app/logseq-omnivore/issues/114#issuecomment-1641978644
