### ISSUE TITLE
Importing article {{{ content }}} stops at first section

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [omnivore-app/logseq-omnivore#114]
Hi!

The link to the article : https://lynettebye.com/blog/2023/4/20/inside-the-minds-of-adhd

Relevant section of the article :
![image](https://github.com/omnivore-app/logseq-omnivore/assets/26625900/786c11a3-0fc2-4344-ad2f-74c4c09978d1)

The imported content stops at the first section:
![image](https://github.com/omnivore-app/logseq-omnivore/assets/26625900/77fc4082-e5b4-44a9-afd6-2cee6d3fe43a)

* I do have highlights that go further down the article.

* I tried deleting the article block, changing the sync date and reimporting to no avail.

* I changed `{{{ content }}}` to `{{ content }}` to no avail.

* Logseq plugin version: 1.13.0

* The saved article is  fine in omnivore android and web

Let me know if I can help provide more information :)

**Comment by jacksonh** [comment]
@thiswillbeyourgithub do you mind opening the markdown of the page in another editor like VS Code, and checking to see if the full content is there?

**Comment by thiswillbeyourgithub** [comment]
I just opened it in vim and confirm that the rest of the article is not there.

**Comment by Asgoret** [comment]
Is there any workaround or something?

**Comment by thiswillbeyourgithub** [comment]
Not that I found. It's a pretty serious issue that can be devastating to one's workflow :/

**Comment by jacksonh** [comment]
I was able to replicate this with the top article, i have a feeling Logseq fails when we import the header elements like 

```
# When you have a task that requires a lot of thought, how often do you avoid or delay getting started?
```

**Comment by thiswillbeyourgithub** [comment]
Oh. I think logseq throws an error when you use "# something" inside a multiline block. Maybe this error is hidden when it's from a plugin ? If that's the issue that's great because that means you can split the content in several blocks as I wished for in #113  :D

**Comment by sywhb** [comment]
Yeah, I believe Logseq still doesn't allow multiple headings or sub-block in the same block so it causes this error.

**Comment by yoghurtdewdew** [comment]
The problem that I found is `{{{ content }}}` could not work. 
I wish to see original content below the Highlights. So the Template of Highlight is set as:

```
> {{{text}}} [⤴️]({{{highlightUrl}}}) {{#labels}} #[[{{{name}}}]] {{/labels}}

{{#note.length}}note:: {{{note}}} {{/note.length}}

[[omnivore original content]]
collapsed:: true
    {{{ content }}}
```

It just could not work at all. 
Hope there will be new options for the page content preferences of this plugin.

**Comment by sywhb** [comment]
Hey @Asgoret sorry for the late reply. Yeah, Logseq has some issues displaying the content in markdown format in a block.

I believe it is because Logseq does not allow nested blocks generated by templates

**Comment by Asgoret** [comment]
@sywhb no worries. Do you know maybe, there is any issue/mr on logseq side? So I can bump it out

**Comment by sywhb** [comment]
@Asgoret I believe I saw one before. Let me look for it

**Comment by hzxsw** [comment]
![image](https://github.com/omnivore-app/logseq-omnivore/assets/141128095/930e10bb-bdfa-412a-afe3-bf85ade1f553)
![image](https://github.com/omnivore-app/logseq-omnivore/assets/141128095/615c93af-0acd-4583-8c28-b506a1f04353)
![image](https://github.com/omnivore-app/logseq-omnivore/assets/141128095/0365b807-3248-447b-a343-a531e498d5d0)
![image](https://github.com/omnivore-app/logseq-omnivore/assets/141128095/fd0bfbdf-fce0-42ea-bb61-6ed825b64caa)

@sywhb Hello, I have encountered the same issue. After conducting some testing and analysis, I suspect that it might be caused by two consecutive line breaks, resulting in the truncation of the text. I hope this information can be helpful in resolving the problem. Thank you.

**Comment by thiswillbeyourgithub** [comment]
@sywhb a simple workaround for now would be to escape the leading # of the text. Either simply adding a space between the newline and #, or backslash in each newline +`#`. Etc. Maybe rrplacing by simply a larger bolded font via inline html?

A more advanced fix would be to split the large block into different blocks, which is apparently more what ligseq was designed to handle anyway. But then you might want each highlight to appear as children of the right block of text, and might run into issue with respecting the template etc. All in all this is more complicated.

I'd really like to have the quick workaround at least because I'm coding a script that automatically creates anki flashcards of my highlights via logseq and this is keeping me stuck. Hence why the quick workaround above :)

**Comment by thiswillbeyourgithub** [comment]
> > I'd really like to have the quick workaround at least because I'm coding a script that automatically creates anki flashcards of my highlights via logseq and this is keeping me stuck. Hence why the quick workaround above :)
> 
> Up :)

Respectful up :)

**Comment by thiswillbeyourgithub** [comment]
That seems to work perfectly! Thank you immensely. I'll tell you more later when I finish creating an automatic flashcard creator based on this. Thanks!

**Comment by sywhb** [comment]
Thanks for the confirmation! @thiswillbeyourgithub 

I finally got time to finish this PR and hopefully it will resolve this issue permanently ~
