### ISSUE TITLE
Syncing article note into logseq

### ISSUE THREAD

**Issue by howarddo2208** [omnivore-app/logseq-omnivore#115]
Hi there, I'm wondering if there is a way to sync the article note into logseq. I checked the integration docs, but I didn't see a variable for article note for the highlight template. Is this feature available or planned?

**Comment by jacksonh** [comment]
Hey @howarddo2208 you can use `{{ note }}` if you have the latest version of the plugin `v1.13.0`

**Comment by howarddo2208** [comment]
Oh, my bad, I was looking at the highlight part only. Btw, I note with bullet list, and it only renders a single line inside logseq.

**Comment by deimidis** [comment]
Hi, I started today with omnivore plugin. I have the v1.13.0 and the template is the default one, but I can't see my notes in logseq, maybe I don't know where to watch:

```
> {{{text}}} [⤴️]({{{highlightUrl}}}) {{#labels}} #[[{{{name}}}]] {{/labels}}

{{#note.length}}note:: {{{note}}}{{/note.length}}
```

Thanks!

**Comment by howarddo2208** [comment]
You look at the wrong section tho, the note variable in the article template is what you're looking for https://docs.omnivore.app/integrations/logseq.html#variables-available-to-the-article-template

**Comment by jacksonh** [comment]
I think we cleared this one up in Discord, @deimidis was trying to sync the highlight notes in but they didn't appear at first in Logseq. Going to close it out but please let me know if anyone is still having issues!
