### ISSUE TITLE
Improve Performance with Batch Block Insert

### ISSUE THREAD

**Issue by briansunter** [omnivore-app/logseq-omnivore#13]
Check out the Batch block insert api to make it faster to sync the articles by inserting a bunch of blocks at once instead of one by one.

https://logseq.github.io/plugins/interfaces/IEditorProxy.html#insertBatchBlock

**Comment by sywhb** [comment]
Hey @briansunter, the batching blocks inserting api previously was not working and I have reported. I'm not sure if they have fixed it but I will give it a try.

**Comment by sywhb** [comment]
Resolved in v1.4.4
