### ISSUE TITLE
Version 1.14.0 does not work

### ISSUE THREAD

**Issue by YU000jp** [omnivore-app/logseq-omnivore#146]
It doesn't work with Logseq. It should be changed to pre-release immediately.

https://github.com/omnivore-app/logseq-omnivore/releases/tag/v1.14.0
I updated to the new version with Logseq and restarted, but it didn't work. Even if I download the zip file from assets on the Release page and load it, it does not work.

**Comment by jacksonh** [comment]
@YU000jp can you say the error you are getting?

**Comment by YU000jp** [comment]
The console only has this information. (Turn off other plugins.)
![image](https://github.com/omnivore-app/logseq-omnivore/assets/111847207/6988e628-94d2-4bc1-8aa7-419be27f1a5f)


Clone the repository, build it and it's created and works. There may be something wrong with the build created with GitHub Actions workflow.

**Comment by YU000jp** [comment]
The toolbar icon is not displayed, and the plugin settings cannot be opened.

**Comment by jacksonh** [comment]
> The toolbar icon is not displayed, and the plugin settings cannot be opened.

Thank you! Seeing the same error

**Comment by gvenusleo** [comment]
After upgrading to the latest version, I had the same issue. Although the version number shown in Logseq is `v1.14.0` , it is still `v1.13.6` in the configuration file.

![image](https://github.com/omnivore-app/logseq-omnivore/assets/79075347/5bc65ff2-62c0-46da-bb5e-52a31107c0df)

![image](https://github.com/omnivore-app/logseq-omnivore/assets/79075347/dc992b91-3a68-43e7-8643-2e3d56a9c883)

**Comment by jacksonh** [comment]
Thanks, we have a fix underway

**Comment by sywhb** [comment]
Hey @YU000jp @gvenusleo, `v1.14.1` is just released to fix this error.

Could you please upgrade and let me know if it works?

**Comment by YU000jp** [comment]
Is good! It works without any problems.

**Comment by sywhb** [comment]
> Is good! It works without any problems.

Awesome! Thanks for the confirmation ❤️

**Comment by YU000jp** [comment]
Thank you very much. Good night. 🫡

**Comment by gvenusleo** [comment]
It works fine, thanks for the fix!
