### ISSUE TITLE
Settings schema Error!

### ISSUE THREAD

**Issue by mkfischer** [omnivore-app/logseq-omnivore#149]
On a Mac running MacOS 14 (Sonoma) and a new install of Logseq (Version 0.9.19 (72)) the plugin for Omnivore does not load and cannot be reloaded by toggling the plugin in the UI.    Attempting to to edit the settings returns a dialog box with:

<img width="898" alt="Screenshot 2023-10-25 at 16 23 30" src="https://github.com/omnivore-app/logseq-omnivore/assets/5872780/d2ffefa4-832f-49af-8f0e-bd06094ecdb3">

**Comment by jacksonh** [comment]
Hi, I've seen this once before where a user's schema file was blank. Can I ask if you use logseq sync?

**Comment by mkfischer** [comment]
I sync with the integrated option.

**Comment by jacksonh** [comment]
@mkfischer i think you can first look at and then delete this file if its fully empty:

```
cat ~/.logseq/settings/logseq-omnivore.json
```

**Comment by mkfischer** [comment]
I backed up the populated file and deleted it.  It worked.
