### ISSUE TITLE
request: make article content collapsed by default or give the choice

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [omnivore-app/logseq-omnivore#156]
Hi,

Thank you very much for adding article content sync into a child block!

But is it possible to make the content and highlight child blocks collapsed by default? Or togglable via a UI checkbox?

Have a nice day!

**Comment by sywhb** [comment]
Hey @thiswillbeyourgithub, yeah this is a good one.

I will make both blocks collapsed by default ~
