### ISSUE TITLE
Setting `headingBlockTitle`  to empty generates extra asterisks

### ISSUE THREAD

**Issue by stephanmax** [omnivore-app/logseq-omnivore#161]
I am super happy about the `headingBlockTitle` setting and I immediately set it to empty. Unfortunately, the plugin now includes a lot of unnecessary asterisks in front of block text:

![screenshot-20231114-110542Z-selected](https://github.com/omnivore-app/logseq-omnivore/assets/334191/9240b11c-0f0d-4351-82fb-87c33b82313a)

**Comment by sywhb** [comment]
Hey @stephanmax, a new version `v1.16.2` is released to address this issue.

Could you please upgrade your plugin, delete the above page in Logseq and resync the article again?

I hope it works!

**Comment by stephanmax** [comment]
Hey @sywhb, thanks for the swift response!

Unfortunately, I still get the same behavior with 1.16.2.

**Comment by sywhb** [comment]
Weird. I couldn't replicate it

**Comment by stephanmax** [comment]
Nevermind—I got it to work! In my first attempt I left the first bullet point of the Omnivore import page in the page which seems to trigger the wrong bulleting. I removed the first bullet/paragraph (not just emptied it) and now it works like a charm. Should have done what you suggested and just deleted the whole page in the first place.

Thanks a mill for your work on this and this wonderful piece of software!

**Comment by stephanmax** [comment]
Hm, I think I need to re-open this. Newly imported items seem to struggle with the same behavior, see the attached screenshot. Can you replicate?

![screenshot-20231210-170410Z-selected](https://github.com/omnivore-app/logseq-omnivore/assets/334191/0bee394f-ba73-4a46-b959-f9bd40b22d82)

**Comment by sywhb** [comment]
No, I could not replicate it and the asterisks seem to be generated by Logseq when I call `bulkInsert` API.

Let me check the code base and see if there is any thing I can do

**Comment by stephanmax** [comment]
Thanks for looking into this again, really appreciate it. Bear in mind that setting `headingBlockTitle` to empty and a non-empty import page (setting `pageName`) trigger that behavior for me.
