### ISSUE TITLE
Failed to fetch

### ISSUE THREAD

**Issue by oleunsonjabi** [omnivore-app/logseq-omnivore#164]
Thanks for all your effort on the plugin. 

I installed the plugin (v1.16.2) on Logseq, added the API Key from Omnivore, and tried to run it on some highlights, but received the error, "Failed to fetch articles." I didn't change anything on the plugin, so I'm wondering what the issue might be. 

FYI: I'm using a MacOS 14.1.1

**Comment by thiswillbeyourgithub** [comment]
Same here. My articles seem to be imported fine though.

**Comment by oleunsonjabi** [comment]
@sywhb Thanks for the quick reply. I did as you said and toggled develop tools to take some screen shots here. I'm not sure if I'm posting shots of the right things. If not, then please tell me and I'll change the photos. 
<img width="1296" alt="Screenshot 2023-11-21 at 09 38 20" src="https://github.com/omnivore-app/logseq-omnivore/assets/74225861/3db57dfa-2649-421d-b042-b36023a26310">
<img width="556" alt="Screenshot 2023-11-21 at 09 38 51" src="https://github.com/omnivore-app/logseq-omnivore/assets/74225861/636a8d81-e892-4029-9914-57d49d92a0e0">
<img width="549" alt="Screenshot 2023-11-21 at 09 39 10" src="https://github.com/omnivore-app/logseq-omnivore/assets/74225861/d6ab1f1d-c009-4e78-af48-4c7049421931">

**Comment by sywhb** [comment]
@oleunsonjabi Yes, this is what I'm looking for. Thank you.

Can you please upgrade the plugin to `v1.16.3` and try again?

**Comment by oleunsonjabi** [comment]
@sywhb Thanks! Just updated and works perfectly! Thank you so much for your quick fix and fast response. Appreciate your work so much!

**Comment by sywhb** [comment]
@oleunsonjabi Thank you again and I will close this issue now
