### ISSUE TITLE
Omnivore plugin stopped working in logseq version 0.10.0

### ISSUE THREAD

**Issue by davidediruscio** [omnivore-app/logseq-omnivore#167]
The plugin is no longer working and the settings page shows the following error:

![image](https://github.com/omnivore-app/logseq-omnivore/assets/2027536/985858bd-a030-4b3c-8382-c359633c09ed)

**Comment by sywhb** [comment]
Hey @davidediruscio, it seems like the config file is corrupted.

Do you know how to navigate to where the file (settings.json) is located?

**Comment by davidediruscio** [comment]
Thanks @sywhb the plugin is working after after removing the logseq-omnivore.json file.
