### ISSUE TITLE
Synchronization with Logseq not working

### ISSUE THREAD

**Issue by shawn1thompson** [omnivore-app/logseq-omnivore#170]
It was working and I'm not sure what happened. I'm using Omnivore in Ungoogled Chromium as a PWA, I've tried reinstalling the plugin and generating a new API key to no avail. The sync appears to happen when I click the toolbar icon as there is some flashing in the Logseq app, but nothing shows up.

**Comment by jacksonh** [comment]
@shawn1thompson can you open the developer console in logseq, sync, and then take a screenshot? Also do you have a customized template?

**Comment by shawn1thompson** [comment]
> @shawn1thompson can you open the developer console in logseq, sync, and then take a screenshot? Also do you have a customized template?

https://bonus01.hwb0307.com/?616d69e17d065ecf#9VcB38LYz8uWMmKXXZyR7PZpiotG7VHkj6hNqe5NNmMU

You should be able to see a screenshot at that link. I'm not using a custom template. Thank you.

**Comment by jacksonh** [comment]
> > @shawn1thompson can you open the developer console in logseq, sync, and then take a screenshot? Also do you have a customized template?
> 
> https://bonus01.hwb0307.com/?616d69e17d065ecf#9VcB38LYz8uWMmKXXZyR7PZpiotG7VHkj6hNqe5NNmMU
> 
> You should be able to see a screenshot at that link. I'm not using a custom template. Thank you.

Sorry do you mind sending again. You can also email it to me jacksonh at omnivore.app

**Comment by remicorniere** [comment]
Hi, not sure if it's the same reason as OP, but here are screenshots for me:
![image](https://github.com/omnivore-app/logseq-omnivore/assets/17186374/c8ffe5aa-4e1d-4728-8380-a65d8060a0fb)
Notice the error messages at the bottom. 
This is when I trigger a sync with the tray icon. Not sure what happens when it "auto-syncs", but I'm guessing it's the same because I cannot have new articles synced anymore.  
I still get the confirmation dialog though:
![image](https://github.com/omnivore-app/logseq-omnivore/assets/17186374/0af2056d-6b48-44b3-b6a1-36764e1ac618)

**Comment by jacksonh** [comment]
> I still get the confirmation dialog though:

Can you also screenshot the console tab?

**Comment by remicorniere** [comment]
Ok that's weird: turns out I was using an old version of logseq (9.19 if I'm not mistaken), and I just updated it to 10.3.  
Now I still can't sync, but I get no error message anymore. Here:  
![image](https://github.com/omnivore-app/logseq-omnivore/assets/17186374/9f54e699-9ec7-4b80-970a-07962aef9716)

So as you see, nothing in console:
![image](https://github.com/omnivore-app/logseq-omnivore/assets/17186374/d7bc9bdc-5568-4f35-9be2-449435314fa9)

**Comment by jacksonh** [comment]
I think the errors might be hidden in your console, can you click on that `Custom Levels` and change it to all?

**Comment by jacksonh** [comment]
Or you might need to click on the gear beside it

**Comment by jacksonh** [comment]
Actually click on this thing and then click on the top item there, it should be like "12 messages" 

<img width="52" alt="Screenshot 2024-01-03 at 19 56 12" src="https://github.com/omnivore-app/logseq-omnivore/assets/75189/4da3822b-8ce2-4eca-abb4-e706386d660a">

**Comment by remicorniere** [comment]
Is this ok ?
![image](https://github.com/omnivore-app/logseq-omnivore/assets/17186374/5f31519f-e3fe-494c-887d-593fc2db4452)

**Comment by jacksonh** [comment]
So no errors there, it looks like it successfully synced around ten minutes ago.

**Comment by remicorniere** [comment]
It does look like it should be ok, but I still cannot find new articles. Usually, I can reference highlights using `(())` and starting typing their content, or I also have a page in logseq with all synced articles.    
  
It still looks like the latest ones were not synced because I cannot find them on the page or reference highlights (I also tried to grep my entire vault outside of logseq, and the articles are not there). Could I provide anything else to help with debugging ?    

I just tried adding a new article since we started discussing (they are imported if they have a specific tag in omnivore, which was not touched) and still no luck.

**Comment by jacksonh** [comment]
> It does look like it should be ok, but I still cannot find new articles. Usually, I can reference highlights using `(())` and starting typing their content, or I also have a page in logseq with all synced articles.
> 
> It still looks like the latest ones were not synced because I cannot find them on the page or reference highlights (I also tried to grep my entire vault outside of logseq, and the articles are not there). Could I provide anything else to help with debugging ?
> 
> I just tried adding a new article since we started discussing (they are imported if they have a specific tag in omnivore, which was not touched) and still no luck.

/cc-ing @sywhb -- i think this might be the issue with search files. @remicorniere which filter are you using to import into Logseq?

**Comment by remicorniere** [comment]
This one: 

![image](https://github.com/omnivore-app/logseq-omnivore/assets/17186374/73c9e11e-c876-4812-a6dd-b80d8a9b1ff9)

**Comment by jacksonh** [comment]
Can you try modifying that to `in:all label:Export_To_Logseq` and then changing the last synced date to be a few days ago to pull in new stuff?

**Comment by sywhb** [comment]
is the label `Export_To_Logseq` or `Export To Logseq`?

**Comment by remicorniere** [comment]
Ha ! So changing the filter and clicking on the tray icon did not do it, but setting the date to a few days ago made it work !  

@sywhb it's the one with underscores

**Comment by sywhb** [comment]
> Ha ! So changing the filter and clicking on the tray icon did not do it, but setting the date to a few days ago made it work !
> 
> @sywhb it's the one with underscores
> 
> EDIT: now it seems to work with the icon. Thanks a lot :)

glad to know it works now 👍

**Comment by shawn1thompson** [comment]
> > @shawn1thompson can you open the developer console in logseq, sync, and then take a screenshot? Also do you have a customized template?
> 
> https://bonus01.hwb0307.com/?616d69e17d065ecf#9VcB38LYz8uWMmKXXZyR7PZpiotG7VHkj6hNqe5NNmMU
> 
> You should be able to see a screenshot at that link. I'm not using a custom template. Thank you.

Sorry for the delay. Sent via email.

**Comment by jacksonh** [comment]
> > > @shawn1thompson can you open the developer console in logseq, sync, and then take a screenshot? Also do you have a customized template?
> > 
> > 
> > https://bonus01.hwb0307.com/?616d69e17d065ecf#9VcB38LYz8uWMmKXXZyR7PZpiotG7VHkj6hNqe5NNmMU
> > You should be able to see a screenshot at that link. I'm not using a custom template. Thank you.
> 
> Sorry for the delay. Sent via email.

Thanks Shawn, i think we have an update that could solve your issue

**Comment by shawn1thompson** [comment]
> > > > @shawn1thompson can you open the developer console in logseq, sync, and then take a screenshot? Also do you have a customized template?
> > > 
> > > 
> > > https://bonus01.hwb0307.com/?616d69e17d065ecf#9VcB38LYz8uWMmKXXZyR7PZpiotG7VHkj6hNqe5NNmMU
> > > You should be able to see a screenshot at that link. I'm not using a custom template. Thank you.
> > 
> > 
> > Sorry for the delay. Sent via email.
> 
> Thanks Shawn, i think we have an update that could solve your issue

The update doesn't seem to be in the Marketplace yet. Can I simply overwrite the files in the plugin directory with the downloaded files from the Releases?

**Comment by jacksonh** [comment]
> > > > > @shawn1thompson can you open the developer console in logseq, sync, and then take a screenshot? Also do you have a customized template?
> > > > 
> > > > 
> > > > https://bonus01.hwb0307.com/?616d69e17d065ecf#9VcB38LYz8uWMmKXXZyR7PZpiotG7VHkj6hNqe5NNmMU
> > > > You should be able to see a screenshot at that link. I'm not using a custom template. Thank you.
> > > 
> > > 
> > > Sorry for the delay. Sent via email.
> > 
> > 
> > Thanks Shawn, i think we have an update that could solve your issue
> 
> The update doesn't seem to be in the Marketplace yet. Can I simply overwrite the files in the plugin directory with the downloaded files from the Releases?

hey shawn sorry for the delay. Is it showing in the marketplace? If not you could change to a custom query and set it to `in:all has:highlights` and then set your sync date to a few days ago to re-sync

**Comment by shawn1thompson** [comment]
It's working now with the update. Thank you.
