### ISSUE TITLE
Logfile? I get permanently "failed to fetch articles" error

### ISSUE THREAD

**Issue by marcfree** [omnivore-app/logseq-omnivore#185]
Hey first, thanks for the great plugin.
Unfortunatly, since recently I can't sync my articles anymore, and the error I get is `failed to fetch articles` There was no change in the API key, just a little update to have date-read in my template. But even returning to the previous version of the template, the sync doesn't work.
How can I check, what's going on?

**Comment by jacksonh** [comment]
> Hey first, thanks for the great plugin. Unfortunatly, since recently I can't sync my articles anymore, and the error I get is `failed to fetch articles` There was no change in the API key, just a little update to have date-read in my template. But even returning to the previous version of the template, the sync doesn't work. How can I check, what's going on?

hi, in logseq you can go "View" -> "Toggle Developer Tools"

**Comment by marcfree** [comment]
Hi, thanks for the advice with the developer tools.
So I've enabled the developer tools and found a log file which says exactly nothing. I've updated to config for Omnivore, and requested the articles - and there is just nothing in the logs.
I found the file `main.log` right here:
`/Users/xy/Library/Logs/Logseq`
and here is the content:
[main2.log](https://github.com/omnivore-app/logseq-omnivore/files/15096996/main2.log)
Spoiler: not one line for Omnivore :(

**Comment by thiswillbeyourgithub** [comment]
(For the record I was already aware of the way to toggle the developper tools but, finding nothing useful for the omnivore plugin, I came to the conclusion that adding a few debug prints would be useful)

**Comment by jacksonh** [comment]
> Hi, thanks for the advice with the developer tools. So I've enabled the developer tools and found a log file which says exactly nothing. I've updated to config for Omnivore, and requested the articles - and there is just nothing in the logs. I found the file `main.log` right here: `/Users/xy/Library/Logs/Logseq` and here is the content: [main2.log](https://github.com/omnivore-app/logseq-omnivore/files/15096996/main2.log) Spoiler: not one line for Omnivore :(

Hi, there should be a console that is printed to in the developer tools. Something like this:

<img width="1774" alt="Screenshot 2024-04-24 at 12 44 24" src="https://github.com/omnivore-app/logseq-omnivore/assets/75189/5ace116a-6acc-49ab-8ab8-35ac8d192f32">

**Comment by marcfree** [comment]
Hi Jackson, thanks again for your help. 
In Logseg I can't find such a console. There are also no commands in the command list or menus ;( (have looked for DEV, Error, Entwickler (DEV in German :) ), failure etc.
Any other idea ?
Thanks, Marc

**Comment by richd67** [comment]
Another Logseq user here with the same problem, no sync for the last 6 days or so? No changes on my side?

**Comment by marcfree** [comment]
I just played around with Wireshark, to figure out, what's going on. And it seems to me, just absolutely nothing.
1st) I tried using the Omnivore-App on MacOS. It calls up the API like desired and fetches the article I've chosen.
2nd) I start LogSeq, and there is no visible package addressed to the API of Omnivore and as such, no error message.
To be sure, I tried yesterday, and had another try today - same result. No outgoing API Call from Logseq-omnivore plugin :(

**Comment by marcfree** [comment]
So, today I have had again a look into this topic. I guess it's a user error (at least on my side).
I've recently added a new field in my `template for new articles`. I pretty sure, it has worked until a previous version, as I wasn't aware of this behaviour. Here's what happened:
First: I found the development console in the Mac Version of Logseq is triggered by `Command-Option-I`. So, I've acitivated Dev-Mode, and started the Dev-Console. Finally, I pressed the "Omnivore" button in Legseq.
The console showed then an error, saying 
<img width="543" alt="image" src="https://github.com/omnivore-app/logseq-omnivore/assets/12841950/31bf823c-d8be-497e-84f9-a409eec467ee">

So, then I had a look here:
https://docs.omnivore.app/integrations/logseq.html#controlling-the-layout-of-the-data-imported-to-logseq
While it was not the first time, I found, that there is different handling for variables and sections - wasn't aware of this. So, I've removed the sections for date-saved, published and read - and voila - Omnivore is syncing again 👍 
Section:
`{{#labels.length}}
labels:: {{#labels}}[[{{{name}}}]] {{/labels}}
{{/labels.length}}`
Fields:
`date-saved:: {{{dateSaved}}} 
date-published:: {{{datePublished}}}
date-read:: {{{dateRead}}}`

**Comment by thiswillbeyourgithub** [comment]
Sadly this is the not case for me

**Comment by richd67** [comment]
Still not working for me??

**Comment by jacksonh** [comment]
> Hi Jackson, thanks again for your help. In Logseg I can't find such a console. There are also no commands in the command list or menus ;( (have looked for DEV, Error, Entwickler (DEV in German :) ), failure etc. Any other idea ? Thanks, Marc

Hey here is a video: https://www.loom.com/share/d404390368e6434db572dc2d837bd4cc
