### ISSUE TITLE
setting up dev environment

### ISSUE THREAD

**Issue by ofer1992** [omnivore-app/logseq-omnivore#192]
Hey, I'm trying to fix a problem in the plugin and I can't seem to get the dev env working. I followed [this guide](https://gist.github.com/xyhp915/bb9f67f5b430ac0da2629d586a3e4d69)
```
npm install
npm run dev
```
But the plugin isn't loaded correctly, says it takes to long. When opening with browser I see an error message that index.ts couldn't be loaded (404). `npm run build` works but then the code is minified etc. What am I missing?

**Comment by sywhb** [comment]
Hey @ofer1992 , we use [pnpm](https://pnpm.io/) instead of npm as the package manager for this plugin.

Could you try to install pnpm first and then run the following command
```
pnpm install
pnpm dev
```
