### ISSUE TITLE
Refactor folder structure

### ISSUE THREAD

**Issue by sywhb** [omnivore-app/logseq-omnivore#28]

**Comment by jacksonh** [comment]
😱  :-)

**Comment by sywhb** [comment]
@jacksonh the current structure is a bit messy. At least I will try to separate code, configs and assets 😞

**Comment by sywhb** [comment]
Maybe tests, too

**Comment by sywhb** [comment]
Closes by 6a524e31f09cd14d06e81409dbeef4a2c553d5af
