### ISSUE TITLE
Highlights 

### ISSUE THREAD

**Issue by vincentteoh** [omnivore-app/logseq-omnivore#32]
Hi, 

I have re-sort the highlights on my logseq but it will back to the original again after syncing. 

How to keep highlight changes in the Omnivore page in Logseq?

Thank you

**Comment by sywhb** [comment]
Hey @vincentteoh thanks for letting us know.

May I check with you if you have made any changes to the highlights or the article in Omnivore after changing the highlights in Logseq?

Any change in Omnivore would be reflected after syncing in Logseq currently.

Please let us know if this is what you want.

**Comment by vincentteoh** [comment]
> Hey @vincentteoh thanks for letting us know.
> 
> May I check with you if you have made any changes to the highlights or the article in Omnivore after changing the highlights in Logseq?
> 
> Any change in Omnivore would be reflected after syncing in Logseq currently.
> 
> Please let us know if this is what you want.

No. only change the highlight on logseq.

**Comment by sywhb** [comment]
Working on some fix in #38 maybe could help to debug this issue

**Comment by sywhb** [comment]
Hey @vincentteoh, v1.6.0 is released. Could you please help to verify if it fixed the issue?
Thank you!
