### ISSUE TITLE
Highlights can't be imported

### ISSUE THREAD

**Issue by kimitrois** [omnivore-app/logseq-omnivore#35]
Everything is default, but no highlights can be imported.
I have no idea if it is a bug or I have just missed some settings.
I have tried to make more highlights and add some notes to it, but only the following would be imported into Logseq.
<img width="683" alt="image" src="https://user-images.githubusercontent.com/93313031/178203587-79aa2a3b-2218-4bf3-beb6-2d0ca5aa9ebd.png">

**Comment by jacksonh** [comment]
Hi @kimitrois can you try clearing the syncAt variable from your settings? You can access it by opening the plugin settings, and clicking `Edit settings json`. Quick demo here: https://www.loom.com/share/acb31e3c7b974819bcb08a7dacd58e3b

**Comment by kimitrois** [comment]
> Hi @kimitrois can you try clearing the syncAt variable from your settings? You can access it by opening the plugin settings, and clicking `Edit settings json`. Quick demo here: https://www.loom.com/share/acb31e3c7b974819bcb08a7dacd58e3b

Hi @jacksonh , thanks for replying. I followed the demo but it still doesn't work. The result is just the same as the former screenshot.

**Comment by sywhb** [comment]
Hey @kimitrois i guess you might need to clear the `filter` in settings.
We are making the filter as a `selectable` config in #37

**Comment by kimitrois** [comment]
> Hey @kimitrois i guess you might need to clear the `filter` in settings.
> We are making the filter as a `selectable` config in #37

Hi @sywhb , I just reinstalled the plugin and cleared the filter but it remains the same.
Thanks for helping...
<img width="472" alt="截屏2022-07-12 21 46 38" src="https://user-images.githubusercontent.com/93313031/178505364-5a045aa0-5b19-40db-961f-fd155bd8e839.png">

**Comment by sywhb** [comment]
@kimitrois  Thanks for your patience. I saw the search api being called by the plugin in our logs: 
```searching pages in elastic {"query":{"bool":{"filter":[{"term":{"userId":"ee7424f6-6c95-11ec-a260-2b9341af2833"}},{"range":{"updatedAt":{"gt":"2022-07-12T13:50:30.000Z"}}}],"should":[],"must_not":[]}},"sort":[{"savedAt":{"order":"asc"}}],"from":0,"size":51,"_source":{"excludes":["originalHtml","content"]}}```

The `updatedAt` in the query is `2022-07-12T13:50:30.000Z` so only articles updated after this timestamp will be fetched.
This might be due to the `synced at` config not updated properly.
May I know if you have any article or highlight saved after `2022-07-12T13:50:30.000Z` so we could verify again?

**Comment by sywhb** [comment]
Got it, thanks @kimitrois .
Yeah the `synced at` would be updated once the syncing is completed.

For the latest fetched article, is there an arrow besides the title? like this:
<img width="924" alt="Screenshot 2022-07-12 at 10 29 40 PM" src="https://user-images.githubusercontent.com/12963965/178515669-e83833d6-3dac-4c8f-8fd3-81bfc142de19.png">

If there is one, clicking on that arrow would expand the highlights and annotations.
<img width="890" alt="Screenshot 2022-07-12 at 10 30 01 PM" src="https://user-images.githubusercontent.com/12963965/178515450-b6beb134-dfb8-4552-8cfd-af8fba50897d.png">

**Comment by kimitrois** [comment]
🤦🏻‍♂️ oh shoot, how stupid I am.............It must have worked well since the first click I made...........I see that arrow in my first screenshot.......
Thanks and also Sorry for your time , both of you @sywhb @jacksonh
