### ISSUE TITLE
Articles not importing

### ISSUE THREAD

**Issue by gammonmark** [omnivore-app/logseq-omnivore#36]
Hello,
I've been using the plugin for a few weeks however after having been away, I noticed the plugin is not successfully importing articles to my LogSeq page (either at intervals or manually). So far I have tried:
- Updated plugin
- Toggling the plugin
- Restarting LogSeq
- Creating a new API and added it to plugin
- Deleted plugin and reinstalled, then added a new API

None of these have resolved the issue. Old article and new ones I have just added to Omnivore are not imported to LogSeq.

**Comment by jacksonh** [comment]
@gammonmark can you open the plugin settings, click `Edit settings json` and clear out the syncAt variable? Quick demo here: https://www.loom.com/share/acb31e3c7b974819bcb08a7dacd58e3b

**Comment by gammonmark** [comment]
Thanks @jacksonh. I did that and don't see any change. Restarted LogSeq. Removed API key and added a new one. No articles imported when attempting manually.

**Comment by jacksonh** [comment]
Thanks @gammonmark do you mind telling me your Omnivore username and I'll look into the logs and see if there is some sort of auth issue?

**Comment by gammonmark** [comment]
Sure @jacksonh. It should be "gammonmark" I believe.

**Comment by jacksonh** [comment]
@gammonmark sorry one more thing, after clearing that syncat did hit the toggle in the bottom right?

<img width="374" alt="Screen Shot 2022-07-11 at 11 08 32" src="https://user-images.githubusercontent.com/75189/178329636-46f776df-2cb1-4535-864d-9e7dc01ab076.png">

**Comment by gammonmark** [comment]
I just tried again with toggling the button as well (and quitting LogSeq, etc). No luck.

**Comment by jacksonh** [comment]
Thanks for trying. I appreciate your patience here.

**Comment by gammonmark** [comment]
I just tried deleting the Omnivore page in my LogSeq. A manual fetch does not bring any articles, the page gets created and I have the "articles" header, but no items.

**Comment by jacksonh** [comment]
@gammonmark do you have any articles with highlights? Right after the initial release we changed the default importing behavior, we are using the `has:highlights` search so it will only import articles that have highlights added to them. This seemed like it was what most users expected.

If you want to import all saved articles, in the settings you can just set that filter to a blank string (just delete everything), and that will import all articles.

**Comment by gammonmark** [comment]
I wondered about that. I did try deleting everything from the filter line, and with it blank I get no articles importing. However, I added highlights to a couple of articles and tried the fetch and those articles  do get imported (with the filter line blank or with it set to `has:highlights`). So highlights seem to be required regardless of the filter set to highlights or set to a blank string.

**Comment by jacksonh** [comment]
@gammonmark ok thanks, that helps a lot. I might need @sywhb's help here so it will probably be a few hours, but looks like we understand the issue now. 

Sorry about the confusion with the filter change.

**Comment by gammonmark** [comment]
All good. Super appreciate the troubleshooting efforts and speedy replies. Let me know if I can be of further help.

**Comment by sywhb** [comment]
Making the filter as a `selectable` config in #37

**Comment by sywhb** [comment]
Hey @gammonmark , v1.6.0 is released. Could you please help to verify if it fixed the issue?
Thank you!

**Comment by gammonmark** [comment]
Hi @sywhb yes, v1.6.0 looks to have resolved my sync issues. Thanks!

**Comment by gammonmark** [comment]
Hi @sywhb unfortunately it looks like I commented too soon that everything is working. After getting a full import of my articles this morning, I have added a couple more (that include highlights) and am unable to fetch those into Logseq. Attached is the settings for my plugin. It doesn't seems to matter which filter I have (import all articles or import with highlights), the new articles aren't coming in. 
![Omnivore](https://user-images.githubusercontent.com/5113951/179060198-b6ee0565-08bc-4e0a-ae1e-3f8fe14f7e09.png)

**Comment by jacksonh** [comment]
Opening this one up so we don't lose it.

**Comment by jacksonh** [comment]
Just looked at logs and this is the query being made. My guess is something with the `updatedAt` filter. Maybe instead of using a timestamp to track we should use the most recently updated item in the current list. So syncAt is actually set something like this pseudo code: `syncAt = savedArticles.max(updatedAt)`


```
{"query":{"bool":{"filter":[{"term":{"userId":"<REMOVED>"}},{"nested":{"path":"highlights","query":{"exists":{"field":"highlights"}}}},{"range":{"updatedAt":{"gt":"2022-07-14T18:53:47.000Z"}}}],"should":[],"must_not":[]}},"sort":[{"savedAt":{"order":"asc"}}],"from":0,"size":51,"_source":{"excludes":["originalHtml","content"]}}
```

**Comment by gammonmark** [comment]
Thanks @jacksonh. Also just FYI as a data point. I did try going into the .json file and clearing the `syncAt variable` since that was recommended before. No luck with that either.

**Comment by jacksonh** [comment]
Thanks @gammonmark after clearing the var did you also toggle to make sure the settings are reloaded? I have a feeling since it uses current time (i think), it can easily just get updated to the current time again.

**Comment by gammonmark** [comment]
Yes, I did toggle after clearing the var.

**Comment by sywhb** [comment]
@gammonmark @jacksonh so sorry to hear that. Could you please try to change the "last sync" time to an older time before the articles were added?

This could be done by clicking on the calendar icon on the `syncAt` settings

**Comment by sywhb** [comment]
Thanks for the feedback @gammonmark

I think clearing the date will make it invalid so it won't help. I will work on a fix to make the empty syncAt a valid option
