### ISSUE TITLE
Not all articles fetched

### ISSUE THREAD

**Issue by ms3056** [omnivore-app/logseq-omnivore#42]
This might be operator error - so apologies in advance - but I have about 20 articles in Omnivore, they were all mostly brought in around the same day or so (I am new to Omnivore) — your plugin is only bringing in 2 articles. I have tried several different filters - including Advanced and in:all: and in:all and so on. 

This might be something that is working as intended and my articles are tagged wrong or something, but I wanted to ask.

**Comment by jacksonh** [comment]
Thanks for reporting @ms3056 Do you mind telling me your Omnivore username?

**Comment by ms3056** [comment]
Hi - my username is HiroMike

**Comment by ms3056** [comment]
I've solved this by going through each article, deleting the tag, re-entering the tag. Since I touched the articles this way, the plugin in Logseq pulled the older articles in. 

New articles seem to come in fine. I suspect people who have a large Omnivore collection of content that turns the plugin on will be mildly frustrated if they have to touch every article. For me it was 10 articles so no worries. 

Let me know if there is anything I can check - I hope this description helps you narrow down the issue.

**Comment by jacksonh** [comment]
Thanks @ms3056 -- just trying to figure out why this occurred. Did you happen to setup the logseq-plugin before you had Omnivore setup? It should automatically sync all your articles the first time, but for some reason here I think your `last synced time` was after the article's most recent update.

**Comment by jacksonh** [comment]
Adding @sywhb here to help diagnose.

**Comment by ms3056** [comment]
@jacksonh — I had Omnivore setup with about 6 articles BEFORE I installed the Logseq plugin. I installed Omnivore on about the 10th of August I believe, and I then installed the Logseq plugin on 13th August. Articles pushed into Omnivore on the 13th (and subsequently) came in fine. I couldn't get articles from the 10th, 11th or 12th to come in until I did the trick where I unset and reset the labels.

**Comment by jacksonh** [comment]
Thanks @ms3056 this case certainly should be supported. We will do some more testing. Really appreciate you digging in and figuring out these details.

**Comment by ms3056** [comment]
Another thought. For some of the articles I had opened them on my iPhone in Raindrop.io and did a "open in" Omnivore on the iPhone. While I saw these articles fine in Omnivore perhaps a property came over - these articles were months old.

**Comment by ms3056** [comment]
Thank you!

**Comment by sywhb** [comment]
Hey @ms3056, thanks for reporting! I have been looking into the logs and it seems the first time you were trying to fetch all the highlights which is the default option of the plugin and it overwrote the `syncAt` to the current timestamp so when you try to fetch all the articles, it wouldn't bring the "old" articles saved before `syncAt`.

We are working on a solution to this problem by allowing users to "re-sync" all the articles on the menu and before we ship it, you could clear the "syncAt" timestamp and sync all the articles manually.
<img width="679" alt="Screenshot 2022-08-16 at 12 03 06 PM" src="https://user-images.githubusercontent.com/12963965/184795665-a0cc5b28-0801-4d35-8dd9-4bfeef4be3ef.png">

cc @jacksonh

**Comment by ms3056** [comment]
Thanks for working with me on this! Everything is syncing nicely now, as
far as I can tell!
