### ISSUE TITLE
multi fetch same articles

### ISSUE THREAD

**Issue by Lycheewe** [omnivore-app/logseq-omnivore#5]
when I click fetch button, articles which have been fetched would be added again on the page, it is not so elegant, I hope you can optimize for this

**Comment by lxxself** [comment]
For me, after clicking the get button, new highlight for the same article will not be updated

**Comment by sywhb** [comment]
> For me, after clicking the get button, new highlight for the same article will not be updated

Yeah. I can replicate this issue with v1.4.0 too.

Thanks for the report. I will work on the fix 👍

**Comment by sywhb** [comment]
Refer to #3
