### ISSUE TITLE
Deleted highlights not syncing

### ISSUE THREAD

**Issue by rodneykranz** [omnivore-app/logseq-omnivore#56]
Deleted highlights or links do not seem to sync in Logseq.  Is this intended?

**Comment by sywhb** [comment]
Hey @rodneykranz, thanks for the reporting.

Deleted links/articles will also be deleted from Logseq.

For highlights, we are doing differently and intend to keep them in Logseq.

Would you mind sharing with us some of the use cases?

Thank you!
cc: @jacksonh

**Comment by rodneykranz** [comment]
I would expect that deleting highlights in Omnivore would also delete in Logseq (or vice versa), just as any "sync" would do in general.  Perhaps sync is not the intended functionality here.  The way it works now, is that I have to delete each highlight I no longer want, in 2 places.  Use case is something like: I'm reviewing and taking notes on highlights in Logseq, and decide to delete a highlight (I notice it is redundant, irrelevant, I don't like it, any reason, etc...).

**Comment by sywhb** [comment]
We don't have a good way to sync deleted highlights for now so probably need to manually delete them.

I will close this for now
