### ISSUE TITLE
Not embedding articles

### ISSUE THREAD

**Issue by yosevu** [omnivore-app/logseq-omnivore#59]
When I click the Omnivore icon to sync articles, this is the result:

<img width="309" alt="Screenshot 2022-12-16 at 3 09 05 PM" src="https://user-images.githubusercontent.com/16216104/208033973-1a8aa555-1edf-4fef-874e-a9185a7091de.png">

I thought it might be because I use `.org` files, but it doesn't work when I switch to `.md` either.

How do I troubleshoot this issue?

Thank you!

**Comment by jacksonh** [comment]
Hi @yosevu, a couple questions:

1. Do you mind taking a screenshot of your plugin settings? (Make sure not to show your API key). For example, this is what mine look like:

<img width="718" alt="Screen Shot 2022-12-16 at 14 13 50" src="https://user-images.githubusercontent.com/75189/208034453-da0f69b0-78d8-4448-a398-672370fd0b1e.png">

Here I mostly want to see your filter and syncAt values

2. Do you have articles saved in Omnivore already?

**Comment by yosevu** [comment]
Sure! And I do have a few articles saved to Omnivore.

Settings:

<img width="671" alt="Screenshot 2022-12-16 at 3 50 25 PM" src="https://user-images.githubusercontent.com/16216104/208039661-9876fc1e-5b21-493c-acc7-120502326c07.png">

**Comment by jacksonh** [comment]
Thanks. Usually the first thing I try when debugging any syncing issues is reseting the `syncAt` value. It does look like it thinks it successfully sync'd a few minutes ago (if you are in Korea timezone). 

Can you set that date to something earlier than your saved articles. For example: if you just signed up yesterday, set that date toe 12/14 and then tap the Omnivore plugin button again?

**Comment by yosevu** [comment]
> Thanks. Usually the first thing I try when debugging any syncing issues is reseting the `syncAt` value. It does look like it thinks it successfully sync'd a few minutes ago (if you are in Korea timezone).
> 
> Can you set that date to something earlier than your saved articles. For example: if you just signed up yesterday, set that date toe 12/14 and then tap the Omnivore plugin button again?

That did it, thanks! Syncing now. Looks like it could be a time zone related bug? I am in Korea (KST).


Additionally, it doesn't look like there is support for `.org` files. I can rename the file to `.md`, but just curious if that is planned or something that can be contributed?

**Comment by jacksonh** [comment]
I suspect maybe it was related to the `.org` -> `.md` switch. I think maybe it tried to sync to `.org` thought it was successful so it set the `syncAt` value, and then when you switched, it thought it was already "caught up".

Honestly, i didn't even know about `.org` mode. We format everything into Markdown so will need to do a little research on this.

**Comment by yosevu** [comment]
Ah, I see. Well thanks for helping me figure it out! And yes Logseq supports org-mode out of the box.

**Comment by jacksonh** [comment]
That is really intersting, thanks. I used to use org-mode for everything in emacs.

I will close this one out and talk to @sywhb about how we should handle org-mode in the plugin. Thanks for helping debug.
