### ISSUE TITLE
Obsidian plugin

### ISSUE THREAD

**Issue by xplosionmind** [omnivore-app/logseq-omnivore#71]
I do not use Logseq, but I am a heavy Obsidian user. Obsidian is extremely similar to Logseq, making an Obsidian Omnivore plugin derived from this might not be too hard.

For sure, I would appreciate it a lot!

**Comment by sywhb** [comment]
Hey @xplosionmind, the PR for the obsidian plugin is under review.

I will let you know once it is approved

**Comment by sywhb** [comment]
The Obsidian plugin has been released in the community so I will close this one as completed.
