### ISSUE TITLE
the highlight label does not work.

### ISSUE THREAD

**Issue by hellspector** [omnivore-app/logseq-omnivore#72]
windows11 
logseq 0.8.17 the latest version by now.
logseq-omnivore 1.11.4 the latest version by now

This template code in the logseq does not work when sync with omnivore.  The same code is working with the article label.
`{{#labels}}[[{{{name}}}]] {{/labels}} `

this image shows the highlight in the logseq
![image](https://user-images.githubusercontent.com/80568889/220157580-0e8dbba5-b8b0-4a00-b2c4-c2b715c9ff5d.png)

this image show the highlight with a tag in the omnivore 
![image](https://user-images.githubusercontent.com/80568889/220157800-601d4fce-ec11-449b-a817-13fbea00f86d.png)

**Comment by sywhb** [comment]
Hey @hellspector, thanks for reporting.

This is a regression bug which I have fixed in #73 

I will add this fix to the next release
