### ISSUE TITLE
Add format for date_saved

### ISSUE THREAD

**Issue by edshamis** [omnivore-app/logseq-omnivore#74]
Currently, the date_saved property is of `Feb 25th, 2023` format. My date format is different (230225). 
When the article is saved to logseq it's shown in date's linked references, but if I click the date lable (Feb 25th, 2023) it leads nowhere since my date format is different.

**Comment by jacksonh** [comment]
Thanks @edshamis we are looking into this one.

**Comment by sywhb** [comment]
Hey @edshamis, the `date_saved` format follows the date format in your global config.

May I know what is this format in your global settings?

**Comment by sywhb** [comment]
Thanks @edshamis, yeah, it is what I meant.

In general, `YY` and `YYYY` represent the local week-numbering year (44, 01, 00, 17) are often confused with `yy` and `yyyy` that represent the calendar year. But I can see Logseq does accept them in the preferred date format so I will accept these in the plugin too.

Is it okay if the `date_saved` will be updated with the correct format only for new items synced in Logseq?

**Comment by edshamis** [comment]
Thank you @sywhb, I wasn't even aware about the week-numbering year. After changing YY->yy and it worked as expected.
 > Is it okay if the date_saved will be updated with the correct format only for new items synced in Logseq?
It's fine for me, thanks

**Comment by sywhb** [comment]
@edshamis That's great to hear!
