### ISSUE TITLE
Allow metadata to be in a child-block

### ISSUE THREAD

**Issue by sywhb** [omnivore-app/logseq-omnivore#78]
Could be defined in template

**Comment by sywhb** [comment]
![image](https://user-images.githubusercontent.com/12963965/223905298-ea96b9bf-f67e-466a-a319-45de1fb43b70.png)

Got this error when trying to have a list in the template

**Comment by sywhb** [comment]
Probably need to examine the template and extract the list and create child-block with logseq api @jacksonh

**Comment by sywhb** [comment]
#87 is included here

**Comment by thiswillbeyourgithub** [comment]
Personnaly, I think it would make more sense to have the content article in a child block from the metadata.

Currently, my omnivore import page on logseq cannot be skimmed by looking at the article names because the article content is in the same block as the title, so cannot be collapsed.
