### ISSUE TITLE
Failed to fetch articles

### ISSUE THREAD

**Issue by auspiciouslink** [omnivore-app/logseq-omnivore#79]
I'm really not sure what I'm doing wrong. I had gotten this set up and working with the API key a week ago, and now it won't work! Clicking the button returns a pop-up "Failed to fetch articles," no further reason given.

What I've tried:

- Made sure the plugin is updated
- Restarted Logseq
- Tried toggling the plugin on and off
- Clicked into the first empty block
- Generated a new API key
- Renamed the page to sync to
- Tried changing my advanced filter away from "label:Logseq" to "import just my highlights"
- Clearing the last time Omnivore was synced
- Setting a last time Omnivore was synced that was before my last article update
- Highlighting something in a new article and applying the tag

I am properly out of ideas :sweat_smile: Hoping you have some!

**Comment by jacksonh** [comment]
@auspiciouslink Can you open the Developer Console in Logseg (go to View menu, then choose `Toggle Developer Tools`), from there can you check the `Console` and `Network` tabs for errors?

Screenshots would be helpful, if you don't want to attach them here can you email them to feedback@omnivore.app ?

**Comment by jacksonh** [comment]
The one other item I would try too is changing the syncAt value in your plugin settings (screenshot below). This is the last time a sync successfully completed, if it is a recent time that means we think we are syncing successfully.

<img width="754" alt="Screen Shot 2023-03-15 at 10 20 45" src="https://user-images.githubusercontent.com/75189/225188173-83fa3a86-8931-475f-9a1d-8bfa3a79ef03.png">

**Comment by auspiciouslink** [comment]
Hi @jacksonh, thanks so much for the Console tip! I didn't even realize there was a View menu with developer tools available.

It was all down to a misplaced } in a tag in my format default that wasn't failing gracefully: Error: Unclosed section "author" at 266"

I was able to get it back running by moving the } ! If there's a way to pass the error into the failure message, that might help relative n00bs like me figure out what's happening in future cases.

**Comment by jacksonh** [comment]
Great! Maybe when there are failures like that we can write more info on the Omnivore page
