### ISSUE TITLE
The articles aren't fetched 

### ISSUE THREAD

**Issue by yfhuang7** [omnivore-app/logseq-omnivore#80]
Hi,

I currently changes the laptop and therefore the system from Windows to iOS. I used omnivore plugin with logseq under Windows without issue. However, when I use it with logseq under iOS, it didn't fetch any articles without any error message - The page was created with the title "## 🔖 Articles" with zero articles included below. Any suggestion of what might go wrong and how to solve this?

Thank you!

**Comment by yfhuang7** [comment]
Hi,

Thanks for helping. Here are the screenshot. Note that for the filter, I also tried the basic - “import just highlight’, and “import all my articles”. But I got the same results (see the attached screen record). Thanks for helping.


￼

￼

I also attache the screen record here for what’s going on when I tried to fetch:
￼

**Comment by emacsbliss** [comment]
I'm seeing the same issue on MacOS as well.

**Comment by sywhb** [comment]
Hey @yfhuang7, sorry for the delay in reply.

I could not view your screenshot here. Could you upload them again? Thanks!

**Comment by yfhuang7** [comment]
repost the screenshots again here, let me know if you still can't see it. 

![image](https://user-images.githubusercontent.com/21115742/229197662-8e54271b-9f5b-467f-a563-3c93c9df1fbf.png)
![image](https://user-images.githubusercontent.com/21115742/229197771-bedc8943-c159-4b6e-8e0d-24ab9c642c5b.png)

https://user-images.githubusercontent.com/21115742/229197913-351c3416-b61c-41ac-a03f-c8e83775e68c.mov

**Comment by sywhb** [comment]
Hey @yfhuang7, thanks for providing the screenshot! The settings look correct to me.

May I know if this is the latest value of `syncAt` in your settings after you clicking on the "sync" button on the ribbon?
<img width="657" alt="Screenshot 2023-04-01 at 10 12 49 AM" src="https://user-images.githubusercontent.com/12963965/229261065-0d663442-2f69-48e3-ba75-62b418000a7a.png">

Also, could you try to clear the `syncAt` value in the settings and try to sync again so I can trace from the logs?

**Comment by yfhuang7** [comment]
I’ve tried clear the `syncAt` value and sync again. It’s still the same. After clicking “sync” button, the `syncAt` was updated to the time when I clicked the sync.

**Comment by sywhb** [comment]
Thanks for trying @yfhuang7 

I finally was able to reproduce this issue. It is actually with the new version of Logseq App (not the system) and it will escape the characters in the plugin settings now.

So, we don't need the slash `\` in the `customQuery` in the plugin settings to escape quotes `"`. I have verified it on my local machine and it works just fine.

To solve it, could you try to remove the slash in here?
<img width="801" alt="Screenshot 2023-04-03 at 4 08 20 PM" src="https://user-images.githubusercontent.com/12963965/229449699-3f6a583e-bf14-4724-b408-6b7b1bfd8e94.png">

And the new `customQuery` looks like this:
<img width="591" alt="Screenshot 2023-04-03 at 4 10 31 PM" src="https://user-images.githubusercontent.com/12963965/229450177-89cdf7aa-2a91-44fd-b742-9c7ab6d3cb45.png">

After updating the settings, you will need to resync the articles. You could either clear `syncAt` and sync.
Or there is a command to resync everything in Omnivore by pressing Command + Shift + P on the keyboard to show the command palette and search for "Resync all Omnivore Articles" and click on it.

<img width="887" alt="Screenshot 2023-04-03 at 4 14 23 PM" src="https://user-images.githubusercontent.com/12963965/229451384-47703819-c7d6-432b-be3f-a092f1bfbd56.png">

**Comment by yfhuang7** [comment]
Yeah! It works now. Thanks for helping out!
