### ISSUE TITLE
Keeps saying "Omnivore is already syncing"

### ISSUE THREAD

**Issue by Wolverine75** [omnivore-app/logseq-omnivore#84]
All parameters are set up but after hitting the Omnivore button a message shows up and says Omnivore is already syncing.
I have tried everything.

**Comment by jacksonh** [comment]
Hi @Wolverine75 can you try opening the plugin settings as JSON, and setting `loading` to false? 

Quick demo of how to open: https://www.loom.com/share/ecf632ebbb5d42b5a3928f9f9b1560f7

**Comment by jacksonh** [comment]
Once that is done, you can also try reloading Logseq. 

<img width="683" alt="reload-logseq" src="https://user-images.githubusercontent.com/75189/227419977-58573970-ceb9-41f1-b12d-7205a41c4762.png">

I think there are more details on this issue here: https://github.com/logseq/logseq/issues/6838

**Comment by danielnbalasoiu** [comment]
It's not clear to me. In which section should I change to `false`?
Thanks!

**Comment by sywhb** [comment]
Hi everyone,

I'm happy to announce that I have fixed the issue related to the plugin in #85. If you're experiencing this issue, please upgrade your version of the plugin to the latest version.

Thank you for your patience and understanding.
