### ISSUE TITLE
Potential bug in Logseq advanced filter import

### ISSUE THREAD

**Issue by dario-ds** [omnivore-app/logseq-omnivore#88]
I have setup my Omnivore plugin to filter what to import into Logseq using labels, but this has unfortunately stopped working.

I'm not entirely sure why—it might very well be user error.

The custom query I use is label:\"Sent to Logseq\"

**Comment by dario-ds** [comment]
Hi @sywhb - that other issue did help thanks!

The issue was the new custom query language that removed the slashes. 

i.e. whereas previously my filter had been `label:\"Sent to Logseq\"`, changing it to `label:"Sent to Logseq"` did the trick!

**Comment by sywhb** [comment]
That's awesome to hear @dario-ds 

I will close this issue
