### ISSUE TITLE
The highlighted Wikipedia footnote displays incorrectly

### ISSUE THREAD

**Issue by artemith** [omnivore-app/logseq-omnivore#89]
The highlighted Wikipedia footnote displays incorrectly.

test url: https://en.wikipedia.org/wiki/President_of_the_United_States
![image](https://user-images.githubusercontent.com/14881525/230337580-88e3df15-1795-4fd6-a8c8-2b17567e3b87.png)

![image](https://user-images.githubusercontent.com/14881525/230337688-67346b73-5ff3-429f-b0d3-1ed50f76a9a8.png)

![image](https://user-images.githubusercontent.com/14881525/230337730-0b6711bc-aa34-4d59-b179-79b8e3b3dc26.png)

![image](https://user-images.githubusercontent.com/14881525/230338474-398672a6-5116-407f-a079-61514d90d476.png)

OS: Windows 10
Omnivore-plugin: 1.11.8
Logseq: 0.9.1

**Comment by jacksonh** [comment]
Thank you, i think in the past we were removing these footnote links. When you originally saved the Wikipedia page, were you using the browser extension or mobile?

**Comment by artemith** [comment]
> Thank you, i think in the past we were removing these footnote links. When you originally saved the Wikipedia page, were you using the browser extension or mobile?

I use Microsoft Edge extension
