### ISSUE TITLE
Navigates to Omnivore Page on scheduled sync

### ISSUE THREAD

**Issue by briansunter** [omnivore-app/logseq-omnivore#9]
Just noticed it pulls me out of my notes during the scheduled sync. Not sure if you can do it in the background.

**Comment by jacksonh** [comment]
Thanks @briansunter we just discovered this one too and are working on a fix.

**Comment by sywhb** [comment]
Hey @briansunter , this has been fixed now in v1.4.3. So now it will sync in background and you can disable the automatic sync by updating the settings to have `frequency: 0`

If you click on the Omnivore icon on the toolbar, it will still redirect you to the Omnivore page.

Please let me know if it makes sense and works for you!
