### ISSUE TITLE
Allow syncing each article to a separate page

### ISSUE THREAD

**Issue by sywhb** [omnivore-app/logseq-omnivore#93]

**Comment by avelino** [comment]
This issue makes a lot of sense, when we have few articles it works well on a single page, but when we use a lot of omnivore keeping everything on a single page (as it is today) I think it is not the best practice to use Logseq

**Comment by jacksonh** [comment]
Hi @avelino I think most people ignore the big page and see their articles as linked references in the journal, but if some people are trying to read on the full page we definitely need another solution as it will become unmanageable.

**Comment by sywhb** [comment]
Hey @avelino , `v1.12.5` has been released to address this issue.

Please refer to this part in the document: https://docs.omnivore.app/integrations/logseq.html#sync-articles-into-a-specific-logseq-page
