### ISSUE TITLE
可以选择不用单独生成页面

### ISSUE THREAD

**Issue by leommjj** [omnivore-app/logseq-omnivore#96]
我只需要节点记录高亮内容

**Comment by sywhb** [comment]
@leommjj 你好，你是指把每天标记的高亮内容同步到当天的日志中吗？而不是像现在这样把所有的高亮内容同步到同一个生成的页面

**Comment by sywhb** [comment]
@leommjj `v1.12.5` 已经发布了，你可以更新你的插件来使用这个新功能。

英文文档：https://docs.omnivore.app/integrations/logseq.html#sync-articles-into-a-specific-logseq-page
